### ISSUE TITLE
***1-on-1 Request***  Topic: Design Patterns.   Issue: Taking requests for patterns you would like to see covered.

### ISSUE THREAD

**Issue by DanielJRaine** [ga-wdi-boston/conference#3]
I realized there are _many_ design patterns I could talk about, but I want to ask which ones I _should_  focus on, either based upon the easiest to illustrate, or those which would be the most useful to know about.

Candidates I've found so far (some of which we've already covered, so I'll only briefly mention them):

Creational Patterns
-   Abstract Factory - Creates an instance of several families of classes
-   Builder - Separates object construction from its representation
-   Factory Method - Creates an instance of several derived classes
-   Prototype - A fully initialized instance to be copied or cloned
-   Singleton - A class of which only a single instance can exist

Structural Patterns
-   Adapter - Match interfaces of different classes
-   Bridge - Separates an object’s interface from its implementation
-   Composite - A tree structure of simple and composite objects
-   Decorator - Add responsibilities to objects dynamically
-   Facade - A single class that represents an entire subsystem
-   Flyweight - A fine-grained instance used for efficient sharing
-   Proxy - An object representing another object

Behavioral Patterns
-   Chain of Responsibility - A way of passing a request between a chain of objects
-   Command - Encapsulate a command request as an object
-   Interpreter - A way to include language elements in a program
-   Iterator - Sequentially access the elements of a collection
-   Mediator - Defines simplified communication between classes
-   Memento - Capture and restore an object's internal state
-   Observer - A way of notifying change to a number of classes
-   State - Alter an object's behavior when its state changes
-   Strategy - Encapsulates an algorithm inside a class
-   Template Method - Defer the exact steps of an algorithm to a subclass
-   Visitor - Defines a new operation to a class without change

Functional Patterns
-   Function passing
-   Filters and pipes
-   Accumulators
-   Memoization
-   Immutability
-   Lazy instantiation

**Comment by payne-chris-r** [comment]
I would say just do what you find most interesting!

**Comment by jrhorn424** [comment]
My $0.02:

>  either based upon the easiest to illustrate
- Singleton
- Command
- Interpreter (think a dice expression parser, e.g. "4d6 keep 3"
- Observer
- Template Method
- Filters and pipes
- Memoization
- Immutability
- Lazy instantiation

> or those which would be the most useful to know about.
- Singleton
- Decorator
- Proxy
- Command
- Observer
- Filters and pipes
- Memoization
- Immutability
- Lazy instantiation

Based on these lists, I'd recommend a well-done treatment of functional programming, perhaps vis a vis Functional Reactive Programming: https://gist.github.com/staltz/868e7e9bc2a7b8c1f754

**Comment by jrhorn424** [comment]
Also, if you wanted to include Observers, they can facilitate communication between objects in a reactive system. Think about your UI as objects, but the data flow as functional programming.

**Comment by DanielJRaine** [comment]
Is Ember Computed an example of an Observer pattern?  (from Chris)

**Comment by DanielJRaine** [comment]
Just had my 1-on-1 with Chris, and these answers give me a good direction to head in.  Feel free to continue the discussion though.
